[package]
name = "rust_hyper"
version = "0.1.0"
authors = ["Aaron Riekenberg <aaron.riekenberg@gmail.com>"]

[dependencies]
hyper = "0.11.2"
futures = "0.1.14"
futures-cpupool = "0.1.5"
log = "0.3.8"
simple_logger = "0.4.0"
