[package]
name = "rust_hyper"
version = "0.1.0"
authors = ["Aaron Riekenberg <aaron.riekenberg@gmail.com>"]

[dependencies]
chrono = "0.4.0"
horrorshow = "0.6.2"
fern = "0.4.3"
futures-cpupool = "0.1.6"
hyper = "0.11.6"
log = "0.3.8"
mime = "0.3.4"
rust-crypto = "0.2.36"
serde = "1.0.15"
serde_derive = "1.0.15"
serde_yaml = "0.7.1"
