[package]
name = "rust_hyper"
version = "0.1.0"
authors = ["Aaron Riekenberg <aaron.riekenberg@gmail.com>"]

[dependencies]
hyper = "0.11.2"
futures = "0.1.14"
futures-cpupool = "0.1.5"
log = "0.3.8"
fern = "0.4.0"
serde = "1.0.11"
serde_derive = "1.0.11"
serde_yaml = "0.7.1"
chrono = "0.4.0"
horrorshow = "0.6.2"
mime = "0.3.2"
