[package]
name = "rust_hyper"
version = "0.1.0"
authors = ["Aaron Riekenberg <aaron.riekenberg@gmail.com>"]

[dependencies]
chrono = "0.4.0"
horrorshow = "0.6.2"
fern = "0.4.2"
futures-cpupool = "0.1.5"
hyper = "0.11.2"
log = "0.3.8"
mime = "0.3.2"
rust-crypto = "0.2.36"
serde = "1.0.11"
serde_derive = "1.0.11"
serde_yaml = "0.7.1"
