[package]
name = "rust_hyper"
version = "0.1.0"
authors = ["Aaron Riekenberg <aaron.riekenberg@gmail.com>"]

[dependencies]
chrono = "0.4.0"
fern = "0.5.5"
futures = "0.1.19"
futures-cpupool = "0.1.8"
horrorshow = "0.6.2"
hyper = "0.11.24"
log = "0.4.1"
mime = "0.3.5"
net2 = "0.2.32"
rust-crypto = "0.2.36"
serde = "1.0.35"
serde_derive = "1.0.35"
serde_yaml = "0.7.3"
tokio-core = "0.1.16"
