[package]
name = "rust_hyper"
version = "0.1.0"
authors = ["Aaron Riekenberg <aaron.riekenberg@gmail.com>"]

[dependencies]
chrono = "0.4.0"
horrorshow = "0.6.2"
fern = "0.5.1"
futures = "0.1.17"
futures-cpupool = "0.1.7"
hyper = "0.11.10"
log = "0.4.0"
mime = "0.3.5"
rust-crypto = "0.2.36"
serde = "1.0.26"
serde_derive = "1.0.26"
serde_yaml = "0.7.3"
