listen_address: 127.0.0.1:8080

main_page_title: Rusty Web

main_page_cache_max_age_seconds: 3600

threads: 8

commands:

- http_path: /ifconfig
  description: ifconfig
  command: ifconfig
  args: []

- http_path: /netstat
  description: netstat
  command: netstat
  args: [-a, -n]

static_paths:

- http_path: /style.css
  fs_path: resources/style.css
  content_type: text/css
  cache_max_age_seconds: 3600
  include_in_main_page: false
