listen_address: 127.0.0.1:8080

main_page_info:
  title: Rusty Web

commands:

- http_path: /ifconfig
  description: ifconfig
  command: ifconfig
  args: []

- http_path: /netstat
  description: netstat
  command: netstat
  args: [-a, -n]

- http_path: /sleep
  description: sleep
  command: sleep
  args: [5]

static_paths:

- http_path: /style.css
  fs_path: resources/style.css
  content_type: text/css
  include_in_main_page: false
