listen_address: 0.0.0.0:8081

main_page_title: Aaron's Raspberry Pi

main_page_cache_max_age_seconds: 3600

threads: 8

commands:

- http_path: /ifconfig
  description: ifconfig
  command: /sbin/ifconfig
  args: []

- http_path: /iwconfig
  description: iwconfig
  command: /sbin/iwconfig
  args: []

- http_path: /netstat
  description: netstat
  command: netstat
  args: [-a, -n]

- http_path: /ntpq
  description: ntpq
  command: ntpq
  args: [-p]

- http_path: /pitemp
  description: pitemp
  command: /home/pi/bin/pitemp.sh
  args: []

- http_path: /tail_output
  description: tail output
  command: tail
  args: [-n, 20, /home/pi/rust_hyper_run/output]

- http_path: /top
  description: top
  command: top
  args: [-b, -n1]

- http_path: /uptime
  description: uptime
  command: uptime
  args: []

- http_path: /vmstat
  description: vmstat
  command: vmstat
  args: []

- http_path: /w
  description: w
  command: w
  args: []

static_paths:

- http_path: /style.css
  fs_path: style.css
  content_type: text/css
  cache_max_age_seconds: 3600
  include_in_main_page: false

- http_path: /favicon.ico
  fs_path: raspberrypi-favicon.ico
  content_type: image/x-icon
  cache_max_age_seconds: 3600
  include_in_main_page: false
